### ISSUE TITLE
Start app very slow and bad FPS on Android device

### ISSUE THREAD

**Issue by vantuan88291** [infinitered/ignite#1613] opened 2021-02-22 03:22 UTC
What's going on?
My device: Sony xzs, android 8.0.0
---

Steps to reproduce

1. Create a new app using ignite
2. yarn and run on Device
3. The first time open app always slow, delay about 30s to 1 minutes to start app, i was using ignite old version before, about version 5.x its ok, not slow. But now with 6.2.0 on the same device was slow, i don't know the reason why.

---

`ignite doctor` results:
version 6.2.0

**Comment by jamonholmgren** [comment] 2021-03-13 21:52
Can you provide a full `ignite doctor`?

**Comment by mzohrab** [comment] 2021-06-14 18:20
I have the same problem. Have several projects that created with Ignite Bowser, every project has the same problem. I didn't pay attention to that as I was focusing on iOS but after finding this issue, I have checked clean react-native project, app launches super faster. I actually missed to see this on my android device :) I am using ignite already one year by the way and still that problem persists. 

`ignite doctor` results

```
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                16 cores     Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 

JavaScript
  node               12.16.2      /usr/local/bin/node 
  npm                6.14.4       /usr/local/bin/npm  
  yarn               1.22.4       /usr/local/bin/yarn 

Ignite
  ignite-cli           3.5.2              /usr/local/bin/ignite                                            
  ignite src           build              /Users/zohrabm/.config/yarn/global/node_modules/ignite-cli/build 
  navigation           react-navigation                                                                    
  generators                                                                                               
                       component          ignite-bowser                                                    
                       model              ignite-bowser                                                    
                       navigator          ignite-bowser                                                    
                       screen             ignite-bowser                                                    
  createdWith          3.5.2                                                                               
  boilerplate          ignite-bowser                                                                       
  boilerplateVersion   5.4.1                                                                               

Android
  java               14           /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.4       
  cocoapods          1.10.0       /usr/local/bin/pod
```

**Comment by jamonholmgren** [comment] 2021-07-14 18:57
@mzohrab It's hard to debug what's happening there. I don't have any particular advice for you at this time. Is there a way you can put some metrics on the startup time to see what exactly is slowing down your initial load? Additionally, have you tried enabling Hermes?

**Comment by mzohrab** [comment] 2021-11-27 15:07
Sorry for late response. I am back with some results that may help everyone with the same issue. As I have stated above that I use bowser boilerplate in all my RN apps, and each one had the same problem. Start up time takes to 15-20 seconds sometimes and freezes several seconds when the initial screen is visible. Nothing did not help (enabling hermes, caching images, removing console usages and etc.). Then, just bypassed the issue as it worked fine on newer android devices. But yesterday, it eventually got on my nerves and I decided to find the culprit. And I found! It is `react-native-keychain` package. It will kill your apps startup performance. If you have an older device (mine is Xiaomi MI 6) it gets worse. The package loads very slow and throws exception multiple times:
` android.security.keystore.StrongBoxUnavailableException`

Keychain is being used in the boilerplate in utils section (app/utils/keychain.ts).
So workarounds would be:
- Simply, if you do not need it, you can remove the package.
- Try alternatives, like https://github.com/mCodex/react-native-sensitive-info/tree/keystore (did not test though)

Additionally, I have found a thread, where the issue is escalated. Check that below.
https://github.com/oblador/react-native-keychain/issues/314

Hope this update would be helpful for someone.

**Comment by vantuan88291** [comment] 2021-12-01 04:32
> Sorry for late response. I am back with some results that may help everyone with the same issue. As I have stated above that I use bowser boilerplate in all my RN apps, and each one had the same problem. Start up time takes to 15-20 seconds sometimes and freezes several seconds when the initial screen is visible. Nothing did not help (enabling hermes, caching images, removing console usages and etc.). Then, just bypassed the issue as it worked fine on newer android devices. But yesterday, it eventually got on my nerves and I decided to find the culprit. And I found! It is `react-native-keychain` package. It will kill your apps startup performance. If you have an older device (mine is Xiaomi MI 6) it gets worse. The package loads very slow and throws exception multiple times: ` android.security.keystore.StrongBoxUnavailableException`
> 
> Keychain is being used in the boilerplate in utils section (app/utils/keychain.ts). So workarounds would be:
> 
> * Simply, if you do not need it, you can remove the package.
> * Try alternatives, like https://github.com/mCodex/react-native-sensitive-info/tree/keystore (did not test though)
> 
> Additionally, I have found a thread, where the issue is escalated. Check that below. [oblador/react-native-keychain#314](https://github.com/oblador/react-native-keychain/issues/314)
> 
> Hope this update would be helpful for someone.

Thank you so much, i resolved this issue by remove react native keychain, so what now @jamonholmgren ? Should we remove it in next PR?

**Comment by frankcalise** [comment] 2022-08-16 00:21
`react-native-keychain` removed in #2003 - will be released in [Ignite v8: Maverick](https://github.com/infinitered/ignite/milestone/19)

Another recommendation for anyone looking for similar functionality would be to check out [Expo's SecureStore](https://docs.expo.dev/versions/latest/sdk/securestore/)

**Closed by frankcalise** 2022-08-16 00:21 UTC
Labels: more info needed, maverick
