### ISSUE TITLE
Failed prop type onRequestClose in Modal

### ISSUE THREAD

**Issue by naaness** [infinitered/ignite#899] opened 2017-03-14 18:57 UTC
The component Modal in DevscreensButton needs the prop onRequestClose, it goes a warning message

**Comment by skellock** [comment] 2017-03-14 19:33
This is a dupe of https://github.com/infinitered/ignite/pull/892.  Thanks for filing.  I haven't gotten around to reviewing it yet.  =)

**Closed by skellock** 2017-03-14 19:33 UTC
Labels: priority: low, status: help wanted, type: bug
