### ISSUE TITLE
10.0.1 with node@20.10 and npm throws error.

### ISSUE THREAD

**Issue by shtefanilie** [infinitered/ignite#2820] opened 2024-10-21 14:40 UTC
### Describe the bug

Trying to start a new project using npm with node@20.10.0 as dependency manager fails with `npm`. 
Yarn or pnpm seem to work fine. 
The following error occurred:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: molloze@0.0.1
npm ERR! Found: eslint-plugin-n@17.11.1
npm ERR! node_modules/eslint-plugin-n
npm ERR!   dev eslint-plugin-n@"^17.10.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-n@"^15.0.0 || ^16.0.0 " from eslint-config-standard@17.1.0
npm ERR! node_modules/eslint-config-standard
npm ERR!   dev eslint-config-standard@"^17.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/USER/.npm/_logs/2024-10-21T14_36_11_809Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/USER/.npm/_logs/2024-10-21T14_36_11_809Z-debug-0.log
```

### Ignite version

10.0.1

### Additional info

```
✅ How do you want to manage Native code? · CNG
✅ Do you want to initialize a git repository? (Y/n) · No
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · No
✅ Which package manager do you want to use? · npm
✅ Do you want to install dependencies? (Y/n) · Yes
✅ [Experimental] Expo Router for navigation? (y/N) · No
✅ [Experimental] the New Architecture? (y/N) · No

System
  platform           darwin
  arch               arm64
  cpu                10 cores     Apple M2 Pro
  directory          SomeName        /Users/USER/Projects/personal/SomeName

JavaScript (and globally-installed packages)
  node                     20.10.0                                   /Users/USER/.nvm/versions/node/v20.10.0/bin/node
  npm                      10.2.3                                    /Users/USER/.nvm/versions/node/v20.10.0/bin/npm
    corepack               0.22.0
    deadfile               2.1.0
    npm                    10.2.3
    pnpm                   9.12.1
    snyk                   1.1293.1
    yarn                   1.22.21
    zx                     7.2.3
  yarn                     1.22.21                                   /Users/USER/.nvm/versions/node/v20.10.0/bin/yarn
  pnpm                     9.10.0                                    /Users/USER/node_modules/.bin/pnpm
                           <no pnpm global package info available>
  bun                      -                                         not installed
  expo                     -                                         not installed

Ignite
  ignite-cli         10.0.1       /Users/USER/.npm/_npx/bec2839915ba8fc3/node_modules/.bin/ignite
  ignite src         build        /Users/USER/.npm/_npx/bec2839915ba8fc3/node_modules/ignite-cli/build

Android
  java               11.0.11      /usr/bin/java
  android home       -            undefined

iOS
  xcode              15.0.1
  cocoapods          1.15.2       /Users/USER/.rbenv/shims/pod

Tools
  git                git version 2.39.3 (Apple Git-145)   /usr/bin/git
```

**Comment by frankcalise** [comment] 2024-10-21 14:47
Duplicate of #2818

**Closed** 2024-10-21 14:47 UTC
Labels: bug
