### ISSUE TITLE
Unable to install Ignite on Mac Machine

### ISSUE THREAD

**Issue by JaiKB** [infinitered/ignite#274] opened 2016-07-27 19:21 UTC
Hey so I was trying to install Ignite on my machine and it worked fine for the first part but when it tried doing npm i -g generator-react-native-ignite in the post install everything whent haywire. This is the error I got

`Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

> react-native-ignite@1.4.0 postinstall /usr/local/lib/node_modules/react-native-ignite
> npm i -g generator-react-native-ignite

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "generator-react-native-ignite"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /Users/jetmobile/.npm/mute-stream/0.0.6/package.tgz.521662761
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open '/Users/jetmobile/.npm/mute-stream/0.0.6/package.tgz.521662761'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open '/Users/jetmobile/.npm/mute-stream/0.0.6/package.tgz.521662761'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/Users/jetmobile/.npm/mute-stream/0.0.6/package.tgz.521662761',
npm ERR!   parent: 'inquirer' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/react-native-ignite/npm-debug.log
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "react-native-ignite"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! react-native-ignite@1.4.0 postinstall: `npm i -g generator-react-native-ignite`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the react-native-ignite@1.4.0 postinstall script 'npm i -g generator-react-native-ignite'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-ignite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i -g generator-react-native-ignite
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-ignite
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-ignite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jetmobile/Documents/Summer Internship/itt-tracker/ITTTracker/npm-debug.log`

**Comment by BrendanFDMoore** [comment] 2016-07-29 12:38
I'm encountering this under Linux as well (Ubuntu 16.04), so it's not just OSX. I did update `npm` to the latest (3.10) and I did try running with and without `sudo`. 

`react-native-ignite` itself appears to install successfully, but the `postinstall` script is where I encounter permission issues.

**Comment by BrendanFDMoore** [comment] 2016-07-29 12:43
Ok, reading less-recent issues this appears to be a dupe of a well-known problem:
https://github.com/infinitered/ignite/issues/226
https://github.com/infinitered/ignite/issues/219

There appear to be a few possible fixes for the `npm` permissions: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by skellock** [comment] 2016-07-29 12:55
Ya, permissions for node.  We see this one quite a bit.   Installing node as root causes lots of problems when installing global packages.

I find that a `brew`-based node install works great.

Closing, but, let us know if you remain stuck.  Click open & we'll try to help.

**Closed by skellock** 2016-07-29 12:55 UTC

**Comment by foodaka** [comment] 2016-08-06 04:18
I cannot install and ive tried both options, using mac osx captain 10.11. I would really like to try this library

npm 3.10.3

node v6.3.1

**Comment by foodaka** [comment] 2016-08-06 05:02
Got it working finally, removed all versions of node and installed with homebrew
