### ISSUE TITLE
Multiple dex files define

### ISSUE THREAD

**Issue by Bitomancer** [infinitered/ignite#371] opened 2016-09-13 18:52 UTC
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.
- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define La
ndroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexM
erger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerg
er.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerg
er.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.j
ava:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:1
89)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuff
ers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.jav
a:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)

Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:dexDebug'.
  
  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
  > xecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe''
  > finished with non-zero exit value 2
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 44.965 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by GantMan** [comment] 2016-09-13 18:55
what version of ignite?  Probably a duplicate of #362

**Comment by Bitomancer** [comment] 2016-09-13 18:57
1.7.1

**Comment by Bitomancer** [comment] 2016-09-13 19:06
Works like a charm! Thanks!

**Comment by GantMan** [comment] 2016-09-13 19:07
That sucks that you had to clean first!   But this seems to be a new issue with latest Android.  I might have to create a script that helps clean things up and include it in the scripts, but glad it is fixed!

Cheers!

**Comment by GantMan** [comment] 2016-10-20 13:20
Blog article on the clean process:
https://patternsandpractices.wordpress.com/2016/10/19/easy-way-to-make-react-native-run-android-work/

**Comment by TimMeade** [comment] 2016-10-21 11:14
Hit this on the latest as of 2016-10-21...

Followed the blog article above.   Perfect except is linux or osx.  Clean is "./gradlew clean"

**Comment by GantMan** [comment] 2016-10-21 14:52
I'm adding this code to 1.9.2 in the hopes of killing this issue.  
![image](https://cloud.githubusercontent.com/assets/997157/19602248/2e7115ae-9772-11e6-8383-cb7358ff207b.png)
### AND
![image](https://cloud.githubusercontent.com/assets/997157/19602685/cd0fa80a-9773-11e6-8b78-99541eff193d.png)

**Comment by GantMan** [comment] 2016-10-25 19:31
looks to me that you haven't setup ANDROID_HOME just yet

https://facebook.github.io/react-native/docs/getting-started.html#3-set-up-paths

**Closed** 2017-02-21 13:13 UTC
Labels: Info Needed
