### ISSUE TITLE
[Maverick] Missing .gitignore?

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#2174] opened 2022-09-17 05:46 UTC
### Describe the bug

When running ignite-new PizzaApp and choosing to create git repoisitory, theres no .gitignore present in the created directories.

this means everything is committed to source control, including `node_modules`....

Is this expected behaviour?

![Screen Shot 2022-09-17 at 5 33 02 PM](https://user-images.githubusercontent.com/7445602/190842444-eecbb46b-f654-432e-aab4-537d084866c6.png)

### Ignite version

8.0.0-beta-5

### Additional info

As per #2170

**Comment by frankcalise** [comment] 2022-09-17 15:02
Hi @juddey thanks for reporting this issue! Can you please confirm that this is just an issue when using `npm` as the package manager? Also if you don't mind, paste the command that gets output in the terminal for the options you used:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/374022/190863468-797413c4-87f4-4f58-a8dc-c4854c3ad319.png">

**Comment by juddey** [comment] 2022-09-18 22:44
Hi Frank,

Here's what I'm running: 

```
npx ignite-cli@next new DemoFrank
```

I select npm, and I noticed I also install deps: 

<img width="384" alt="Screen Shot 2022-09-19 at 10 39 46 AM" src="https://user-images.githubusercontent.com/7445602/190931255-a3e38369-7492-4a00-84b0-b06d36b9d6fe.png">

To eliminate the deps difference I created a repo and did not install deps:

<img width="519" alt="Screen Shot 2022-09-19 at 10 43 27 AM" src="https://user-images.githubusercontent.com/7445602/190931313-8ea3e372-3a2e-45ce-afd8-1b90748d3b85.png">

As for the question about the yarn package manager, I've found that I can't have yarn on my system and have ignite successfully create a new app. I think it gets confused about the node source, as yarn also installs a node reference of some kind...

However, if you're able to install with yarn and still get a .gitignore then that's enough of an indicator that its restricted to npm 😄

**Comment by frankcalise** [comment] 2022-09-19 19:26
@juddey I can't seem to reproduce this, can you run `npx ignite-cli@next doctor` from the project directory for some extra info and paste it here?

**Comment by juddey** [comment] 2022-09-19 21:54
Sure!

```
Jocelyns-Mini:DemoFrank Justin$ npx ignite-cli@next doctor
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                12 cores     Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz 
  directory          DemoFrank    /Users/Justin/projects/DemoFrank         

JavaScript (and globally-installed packages)
  node                           14.20.0      /usr/local/opt/node@14/bin/node 
  npm                            6.14.17      /usr/local/opt/node@14/bin/npm  
    chromedriver                 91.0.1                                       
    detox                        15.1.2                                       
    detox-cli                    17.4.3                                       
    ignite-cli                   2.2.2                                        
    ios-deploy                   1.9.4                                        
    npm                          8.19.1                                       
    puppeteer                    6.0.0                                        
    puppeteer-pdf                1.2.0                                        
    react-native-clean-project   4.0.1                                        
    react-native-cli             2.0.1                                        
  yarn                           -            not installed                   
  pnpm                           -            not installed                   
  expo                           46.0.10      managed                         

Ignite
  ignite-cli         8.0.0-beta.5   /Users/Justin/.npm/_npx/48400/bin/ignite                        
  ignite src         build          /Users/Justin/.npm/_npx/48400/lib/node_modules/ignite-cli/build 

Android
  java               -            not installed 
  android home       -            undefined     

iOS
  xcode              14.0       
  cocoapods          1.11.3       /Users/Justin/.gem/ruby/2.7.6/bin/pod 
  ```

If this doesn't help and you can't replicate easily then don't worry too much about it

Sometimes strange things happen in the world of computer voodoo 👍

**Comment by jamonholmgren** [comment] 2022-09-20 03:04
This just happened to me too. I think it's because we removed the `.gitignore.template` file for some reason. cc @joshuayoes.

**Comment by yulolimum** [comment] 2022-09-20 03:45
For context: https://github.com/infinitered/ignite/pull/1781

**Comment by joshuayoes** [comment] 2022-09-20 18:02
I ran 
```
yarn build
npm pack
``` 

Then unzipped the tarball and opened it up, it appears that `.gitignore` and `.gitignore.template` are getting copied into the tarball

<img width="286" alt="Screen Shot 2022-09-20 at 11 01 12 AM" src="https://user-images.githubusercontent.com/37849890/191331041-a26f2e61-34bc-42ad-9f92-f897a0273f95.png">

**Comment by joshuayoes** [comment] 2022-09-20 18:05
However, I am getting the described behavior in the issue with
```
npx ignite-cli@8.0.0-beta.6 new PizzaApp --bundle=com.pizzaapp --git --install-deps=false --packager=yarn --target-path=./PizzaApp --overwrite --debug
```

**Comment by joshuayoes** [comment] 2022-09-20 18:12
<img width="569" alt="Screen Shot 2022-09-20 at 11 11 42 AM" src="https://user-images.githubusercontent.com/37849890/191332909-86f015b9-12de-473d-ae0c-0e8bc9a1184a.png">

`.gitignore.template` is getting copied, so for some reason it's not getting copied after `npx ignite-cli@next new`

**Comment by joshuayoes** [comment] 2022-09-21 23:20
@juddey 8.0.0-beta.7 is out now with a PR that should resolve this. Can you try again with `npx ignite-cli@next new`?

**Comment by joshuayoes** [comment] 2022-09-21 23:30
I'm going to close this issue for now. But if you are still having issues with it on the latest version, feel free to re-open it

**Closed by joshuayoes** 2022-09-21 23:30 UTC
Labels: bug, critical, maverick, cli
