### ISSUE TITLE
Error: Command failed with exit code 1: which unix2dos 'which' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Markos21** [infinitered/ignite#2553] opened 2023-11-15 09:17 UTC
### Describe the bug

The following error occurred:

    Error: Command failed with exit code 1: which unix2dos
'which' is not recognized as an internal or external command,
operable program or batch file.

### Ignite version

 8.11.2

### Additional info

System
  platform           win32
  arch               x64
  cpu                4 cores        Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  directory          PROJECT-TASK   F:\PROJECT-TASK

JavaScript (and globally-installed packages)
  node                        18.16.1                                   C:\Program Files\nodejs\node.EXE
  npm                         8.1.2                                     C:\Program Files\nodejs\npm.CMD
    @angular/cli              10.2.0
    @expo/ngrok               4.1.0
    @ionic/cli                6.11.0
    cordova                   9.0.0
    create-react-app          5.0.1
    create-react-native-app   3.9.0
    eas-cli                   5.2.0
    expo-cli                  6.3.10
    firebase-tools            9.18.0
    native-run                1.0.0
    npm                       8.1.2
    pnpm                      8.10.5
    typescript                4.0.5
  yarn                        -                                         not installed
  pnpm                        8.10.5                                    C:\Users\Mark\AppData\Roaming\npm\pnpm.CMD
                              <no pnpm global package info available>
  expo                        -                                         not installed

Ignite
  ignite-cli         8.11.2       C:\Users\Mark\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\Mark\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               11.0.18      C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\bin\java.EXE
  android home       -            C:\Users\Mark\AppData\Local\Android\Sdk

Tools
  git                git version 2.41.0.windows.1   C:\Program Files\Git\cmd\git.EXE

**Comment by frankcalise** [comment] 2023-11-15 13:41
Duplicate of #2551

**Closed** 2023-11-15 13:41 UTC
Labels: bug
