### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by zagnut007** [infinitered/ignite#246] opened 2016-07-13 13:03 UTC
I'm seeing the following error when trying to install via npm. I made sure to update my npm and node packages to the latest version.

`> npm i -g generator-react-native-ignite

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "generator-react-native-ignite"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! path /var/root/.npm/generator-react-native-ignite/1.3.0/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/var/root/.npm/generator-react-native-ignite/1.3.0/package'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, mkdir '/var/root/.npm/generator-react-native-ignite/1.3.0/package'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/var/root/.npm/generator-react-native-ignite/1.3.0/package' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/react-native-ignite/npm-debug.log
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "react-native-ignite"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! react-native-ignite@1.3.0 postinstall: `npm i -g generator-react-native-ignite`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the react-native-ignite@1.3.0 postinstall script 'npm i -g generator-react-native-ignite'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-ignite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i -g generator-react-native-ignite
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-ignite
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-ignite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevinblank/Documents/htdocs/npm-debug.log
npm ERR! code 1
`

**Comment by skellock** [comment] 2016-07-13 13:12
This is a duplicate of https://github.com/infinitered/ignite/issues/219.  When you install `node` as root, it triggers issues like this.  Check out that issue for some solutions.

**Closed by skellock** 2016-07-13 13:12 UTC
