### ISSUE TITLE
Installed Build Tools revision 33.0.0 is corrupted. Remove and install again using the SDK Manager.

### ISSUE THREAD

**Issue by HAFDIAHMED** [infinitered/ignite#2506] opened 2023-09-28 15:15 UTC
### Describe the bug

i got this error any time i create a new application with ignite ...the problem is i  Remove and install again using the SDK Manager.
still the same issue any time i did it 

### Ignite version

latest

### Additional info

i got this error any time i create a new application with ignite ...the problem is i  Remove and install again using the SDK Manager.
still the same issue any time i did it

**Comment by HAFDIAHMED** [comment] 2023-09-28 15:21
up

**Comment by HAFDIAHMED** [comment] 2023-09-28 15:21
up

**Comment by frankcalise** [comment] 2023-09-28 15:28
Can you provide a screenshot or log? I'm not quite following what the issue is here. Also please output the `npx ignite-cli doctor` output as the issue template describes.

Also, I'm kindly asking you to please refrain from "up voting" your own issue every minute. Provide more information and we will do our best to help out. Thank you

**Comment by HAFDIAHMED** [comment] 2023-09-28 15:35
> Can you provide a screenshot or log? I'm not quite following what the issue is here. Also please output the `npx ignite-cli doctor` output as the issue template describes.
> 
> Also, I'm kindly asking you to please refrain from "up voting" your own issue every minute. Provide more information and we will do our best to help out. Thank you

![image](https://github.com/infinitered/ignite/assets/58536023/82c9ac30-6806-49c8-85cb-28924ab8efb0)

**Comment by HAFDIAHMED** [comment] 2023-09-28 16:12
updates please

**Comment by markrickert** [comment] 2023-09-28 21:05
@HAFDIAHMED try igniting a new app on the `next` channel: `npx ignite-cli@next new AppName`. We're closing in on the new version of ignite and the `next` version might be more reliable for newer versions of react-native.

**Comment by HAFDIAHMED** [comment] 2023-09-29 13:36
> @HAFDIAHMED try igniting a new app on the `next` channel: `npx ignite-cli@next new AppName`. We're closing in on the new version of ignite and the `next` version might be more reliable for newer versions of react-native.

@markrickert  please this command """npx ignite-cli@next new AppName""" it generates only android i need the both ios and android pleaaaaaase ????

**Comment by HAFDIAHMED** [comment] 2023-09-29 13:36
up

**Comment by markrickert** [comment] 2023-09-29 15:51
@HAFDIAHMED I noticed from your screenshot above that you're using windows (`C:\`). It is impossible to run an iOS app on windows without some kind of virtualization environment and Mac OS.

This is a limitation placed on Windows by Apple and not a problem with react-native or the ignite boilerplate.

In order to build and run an app on a simulator or real iOS device, you're going to need a Mac computer or a VM running Mac OS so that you can install Xcode and related build tools that are required for iOS apps.

For now, you can work on developing your app in the windows ecosystem on android and then when you're ready, see if it looks and works the same on iOS using a Mac (it should) before you release the app.

**Closed by markrickert** 2023-09-29 15:51 UTC
Labels: bug, invalid

**Comment by HAFDIAHMED** [comment] 2023-09-29 15:56
> @HAFDIAHMED I noticed from your screenshot above that you're using windows (`C:\`). It is impossible to run an iOS app on windows without some kind of virtualization environment and Mac OS.
> 
> This is a limitation placed on Windows by Apple and not a problem with react-native or the ignite boilerplate.
> 
> In order to build and run an app on a simulator or real iOS device, you're going to need a Mac computer or a VM running Mac OS so that you can install Xcode and related build tools that are required for iOS apps.
> 
> For now, you can work on developing your app in the windows ecosystem on android and then when you're ready, see if it looks and works the same on iOS using a Mac (it should) before you release the app.

yes you are totaly right but why there no ios folder ?

**Comment by frankcalise** [comment] 2023-09-29 15:58
@HAFDIAHMED are you using ignite-cli@next? There is no iOS folder if you chose Expo Go, as it's entirely Expo experience and you won't have access to native code.

If you need that, choose the DIY option

**Comment by HAFDIAHMED** [comment] 2023-09-29 16:00
> @HAFDIAHMED are you using ignite-cli@next? There is no iOS folder if you chose Expo Go, as it's entirely Expo experience and you won't have access to native code.
> 
> If you need that, choose the DIY option

yes i did all the options : for expo and expo go and DIY ..every time i got not folder for ios ?

**Comment by frankcalise** [comment] 2023-09-29 16:57
The reason being is that you're on Windows, Expo prebuild will not generate the ios directory as it cannot produce a finished product, since it can't install cocoapods, etc.

**Comment by HAFDIAHMED** [comment] 2023-09-29 17:09
> The reason being is that you're on Windows, Expo prebuild will not generate the ios directory as it cannot produce a finished product, since it can't install cocoapods, etc.

so what is the solution if i want generate with folder ios in windows ?

**Comment by frankcalise** [comment] 2023-09-29 17:24
Have a team member who has macOS clone down the repo and run `npx expo prebuild --platform ios` would be one way.

Or build on EAS servers since they're capable of outputting an iOS app
