### ISSUE TITLE
IOS: Library not loaded: @rpath/hermes.framework/hermes issue

### ISSUE THREAD

**Issue by savaskalkan** [infinitered/ignite#2369] opened 2023-02-04 17:50 UTC
### Describe the bug

After create RN app you are going to see error during IOS building like following

"Library not loaded: @rpath/hermes.framework/hermes"

But I have a solution I want to add here to see anyone needs this.

<img width="189" alt="image" src="https://user-images.githubusercontent.com/12950142/216782046-c2f9deb5-2e67-466d-9dfd-f5953866eb85.png">

Solution is adding hermes.xcframework file to

xcode > build phases > Link binary with Libraries

just press to + sign and search for hermes

And then

You will need to Embed & Sign hermes framework and then build again using command.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/12950142/216782017-fee95a27-44dc-4c31-9f09-47e271709e32.png">

### Ignite version

7.15.9

### Additional info

It is only encountered during react native cli build.

**Comment by frankcalise** [comment] 2023-02-08 12:41
@savaskalkan this is quite an older Ignite version, would you mind trying the latest 8.5.1?

**Comment by pqv2210** [comment] 2023-02-14 06:10
@frankcalise i can confirm that i'm using ignite-cli v8.5.1 to generate new project and this error still exist.
i'm create new project only and run, i don't add anything with new project.

**Comment by frankcalise** [comment] 2023-05-23 11:04
Can you explain your build steps via command-line versus Xcode?

If you could, maybe make a PR addressing this change?

**Comment by frankcalise** [comment] 2023-10-23 11:05
Closing this as it looks like you've found your way. 

If still experiencing issues feel free to re-open the issue.

**Closed by frankcalise** 2023-10-23 11:05 UTC
Labels: bug
