### ISSUE TITLE
Add ignite-debug.log for logging failed commands

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#909] opened 2017-03-18 15:26 UTC
If a user is on *NIX we should have ignite doctor print out `$?` since there's a chance that the error code we emit could be captured there.

BETTER yet, is we make an ignite-debug.log in the ignite folder on failed commands.   It gets timestamped, and when you ignite doctor, it can say "last error was BLAH, 5m ago"   That would make all ignite doctor commands wayyyy better.

**Comment by skellock** [comment] 2017-03-20 15:15
I like the logging feature.  And the doctor tie-in.  The `$?` would be too late to capture the `ignite new` problems, but the logging would fix that.

I have [a logging issue](https://github.com/infinitered/gluegun/issues/161) open on gluegun for support like this.

**Comment by jamonholmgren** [comment] 2017-05-18 04:45
Duplicate of #623.

**Closed by jamonholmgren** 2017-05-18 04:45 UTC
Labels: enhancement, help wanted
