### ISSUE TITLE
I don't have any screen (except launch Screen with Rocket icon) when I create ignite new myapp

### ISSUE THREAD

**Issue by boyinfotronics** [infinitered/ignite#1082] opened 2017-06-08 09:10 UTC
I don't have any screen (except launch Screen with Rocket icon) when I create ignite new myapp
I choose all yes on generate CLI Screen (already choose dev mode)
But i don't have "OPEN DEVSCREENS"  button
like a in this vdo  [](https://www.youtube.com/watch?v=lv00UOXxy0g&t=3s)
(Building a React Native App in Under 15 Minutes)
![screen](https://user-images.githubusercontent.com/25657869/26921042-fecaa93e-4c64-11e7-8d90-aa1c0af1693b.png)

**Comment by GantMan** [comment] 2017-06-08 13:44
## 2 questions to help us here:

did you say YES to dev screens during the setup process?

Do you have dev screens in your `./ignite` folder?

**Comment by boyinfotronics** [comment] 2017-06-08 13:50
Yes . I choose yes on setup process 
I do it repeat 3 time . In 3 project but it's all same thing like that .
![screenignite](https://user-images.githubusercontent.com/25657869/26931827-f29cc0c6-4c8b-11e7-8739-9577a667078d.png)
I need more screen like ignite 2 tutorial

**Comment by GantMan** [comment] 2017-06-08 13:54
It looks like you might have said "NO" to development screens.

`ignite add dev-screens` to fix.

**Comment by ljuborados** [comment] 2017-06-08 18:21
I'm running this under Windows 10, same error, I DID SELECT Yes on the setup process, twice.
Worked after ignite add dev-screens so thanks!

**Comment by caxco93** [comment] 2017-06-09 00:37
cool i was about to post the same thing. it apparently ignores YES on windows

**Comment by mathieuhasum** [comment] 2017-06-10 21:51
Same issue here on Windows 10.
Tried Powershell as well as the old console and even Git Bash.
Had to install manually.

**Comment by akuma06** [comment] 2017-06-11 14:33
Same issue as @mathieuhasum

**Comment by GantMan** [comment] 2017-06-11 15:46
Everyone on windows eh?   Need to boot up my VM to fix this one.

**Comment by ljuborados** [comment] 2017-06-11 15:56
Yeah well, still saving up for a Mac..

**Comment by anderm** [comment] 2017-06-15 04:32
Same issue, I see a few errors during the setup process:
`🔥 igniting app ReactHpm
√ using the Infinite Red boilerplate v2 (code name 'Andross')
√ added React Native 0.42.3 in 57.24s
√ added ignite-ir-boilerplate in 10.77s
The filename, directory name, or volume label syntax is incorrect.
/ ▸ linking
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.

√ configured git
√ ignited ReactHpm in 70.84s`

**Comment by mathieuhasum** [comment] 2017-06-15 07:47
Haha good luck with that @GantMan :)

**Comment by tugrulcan** [comment] 2017-06-16 14:11
Error after running `ignite add dev-screens` 

![image](https://user-images.githubusercontent.com/12617804/27230038-8ff08210-52b6-11e7-83d3-02456bc8b6b9.png)

@GantMan Maybe this is related with problem?

**Comment by caxco93** [comment] 2017-06-17 05:30
@tugrulcan i had that too. simply close the react packager and run that again. it should work

**Comment by skellock** [comment] 2017-06-20 09:52
Anyone still having this issue?

**Comment by smartcris** [comment] 2017-06-20 14:49
I got this bug in windows 8.1 too....and my editors changes are not reflected on the device.

2.0.0-rc.2

**Comment by endru-ralali** [comment] 2017-07-11 05:57
Same here. I use Windows 10.
At the end, I compiled manually from the source code on GitHub using yarn, and... it works.
The "Open DevScreens" button and all the demo appear.

The ignite binary cannot be run directly. So, need to use node:
`node ignite new MyApp`

**Comment by RobertoE91** [comment] 2017-09-17 21:10
Select with SPACE then ENTER

**Comment by nosizejosh** [comment] 2017-09-22 09:43
just started with ignite and I am facing same issues. Run the setup twice, chose yes for dev screens but none appeared. * windows 10.

**Comment by GantMan** [comment] 2017-09-22 13:21
But when you add them after the fact it works?   

Please verify that.

I might have to kick open my windows VM and check.  Though it would be epic if @kevinvangelder could help here.

**Comment by nosizejosh** [comment] 2017-09-22 14:15
@GantMan it works if you add manually, shut down packager and re-run. I have only tried dev-screens. 
NB: The SPACE method suggested by @RobertoE91 doesnt work, at least not for me.

**Comment by anshchauhan** [comment] 2017-10-04 13:05
I'm having same issue in mac. Any resolution?

**Comment by GantMan** [comment] 2017-10-04 13:43
@anshchauhan - when you install dev-screens by hand does it show up?

Also, what OS are you on?

**Comment by anshchauhan** [comment] 2017-10-05 06:06
@GantMan I was on Sierra. I found the solution though.
When I created a new app and ran it, I was getting this error "unable to load script from assets index.android.bundle"

After I applied the given solution here:
https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows 
the app was opening fine but dev screens were not showing. 

Then I created a new app and I removed --dev false option from the given solution and I got my screens.

**Comment by puzpuz** [comment] 2017-10-05 11:29
Windows 10 here, and experience same issue, say YES to all options but:
- no dev screen
- react-native-vector-icons, i18n, and animatable  not installed ( Not linked and not installed)

**Comment by Pixelartist** [comment] 2017-10-17 20:00
Hello there,

same issue for me.

> System
>   platform           win32
>   arch               x64
>   cpu                8 cores               Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
>   directory          H:\projects\myproject
> 
> JavaScript
>   node               8.5.0        G:\Program Files\nodejs\node.EXE
>   npm                5.5.1        G:\Program Files\nodejs\npm.CMD
>   yarn               1.0.2        G:\Program Files (x86)\Yarn\bin\yarn.CMD
> 
> React Native
>   react-native-cli   2.0.1
>   app rn version     0.47.2
> 
> Ignite
>   ignite             2.0.0        C:\Users\bioth\AppData\Roaming\npm\ignite.CMD
> 
> Android
>   java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
>   android home       -            G:\androidsdk

After installing plugins manually it works.

**Comment by cihadturhan** [comment] 2017-11-28 16:14
Lol, I already started my project and didn't know there were more screens haha. I was wondering why all these github services and fixtures exist.  Again, windows 10 here.

**Comment by GantMan** [comment] 2017-11-30 16:19
@kevinvangelder - you're our only hope!  :D

**Comment by effexts** [comment] 2018-10-04 15:15
I was having the same issue, but on mac... using latest version of node. (v10.11.0 i think).

Switching to node 7.6.0 finally added the DevScreens files in the ignite folder. 

I  haven't tested other versions of node.

**Comment by mlaco** [comment] 2018-11-08 16:24
Hey everyone thank you for your patience! I've discovered the root cause and I'll make a PR asap!

**Comment by mlaco** [comment] 2018-11-19 16:49
This is the workaround I used to get dev-screens to show up on Windows, unfortunately
it is NO LONGER WORKING for me today. I am stumped, and I'm officially giving up trying
to fix this until I get some outside help. However, I will still post this. The inconsistency
must mean that I made some other changes that I didn't realize were necessary. (cc @jamonholmgren )



Clone `ignite-dev-screens` to inside `/Users/<your name>/.ignite/overrides/`

Clone `ignite` to a directory `/path/to/my/ignite`

Change `ignite` to `/path/to/my/ignite/bin/ignite` on this line:

`https://github.com/infinitered/ignite-ir-boilerplate-andross/blob/master/boilerplate.js#L178`

then create an app normally

**Comment by knightramza** [comment] 2018-11-22 03:44
> We are planning to re-address this soon!

thanks for your help, this problem break my head for few hours jeje

**Comment by jamonholmgren** [comment] 2018-12-19 22:47
This should be fixed with the latest Ignite CLI and [Ignite Andross 3.0.2](https://github.com/infinitered/ignite-andross/pull/238#issuecomment-448410297).

**Closed by jamonholmgren** 2018-12-19 22:47 UTC
Labels: bug, windows

**Comment by jazst21** [comment] 2019-01-02 07:06
> It looks like you might have said "NO" to development screens.
> 
> `ignite add dev-screens` to fix.

not working on mac mojave. perhaps need to rollback to node 7?  ignite doctor :
System
  platform           darwin                                                                            
  arch               x64                                                                               
  cpu                4 cores                       Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz  
  directory          /Users/pugar/GitHub/ignite1                                                       

JavaScript
  node               10.7.0       /usr/local/bin/node  
  npm                6.4.1        /usr/local/bin/npm   
  yarn               1.12.3       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.57.7      

Ignite
  ignite             2.1.8            /usr/local/bin/ignite  
  boilerplate        ignite-andross                                    

Android
  java               1.8.0_191    /usr/bin/java              
  android home       -            /Users/pugar/android-sdks  

iOS
  xcode              7.0
