### ISSUE TITLE
ignite new should expand '~' for the boilerplate argument

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite#1000] opened 2017-04-27 19:21 UTC
---
What's going on?

ignite new `<name of new project>` --boilerplate=`~\path\to\boilerplate` fails to expand to `\Users\<name of user>`

![screen shot 2017-04-27 at 12 14 44 pm](https://cloud.githubusercontent.com/assets/144869/25500309/672b20fa-2b43-11e7-89ec-21c76e56cab2.png)

The boilerplate option works fine if provide a full path:

ignite new `<name of new project>` --boilerplate=`\Users\<name of user>\path\to\boilerplate`

---
Steps to reproduce

Ignite a new project with a boilerplate option that begins with '~'
---
`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                              Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  directory          /Users/derekgreenberg/Documents/Ignite2Experiments

JavaScript
  node               7.7.4        /usr/local/bin/node
  npm                4.1.2        /usr/local/bin/npm
  yarn               0.23.2       /Users/derekgreenberg/.yarn/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-beta.8   /Users/derekgreenberg/.node/bin/ignite

Android
  java               1.8.0_73     /usr/bin/java
  android home       -            /usr/local/opt/android-sdk

iOS
  xcode              8.3.2
```

**Comment by jamonholmgren** [comment] 2017-04-27 20:12
I think this is related to #985, @derekgreenberg.

**Comment by jamonholmgren** [comment] 2017-05-09 06:04
Closing as duplicate of #985.

**Closed by jamonholmgren** 2017-05-09 06:04 UTC
Labels: bug, low priority
