### ISSUE TITLE
Error during Ignite project setup: rm command not recognized on Windows

### ISSUE THREAD

**Issue by bishallamichhane44** [infinitered/ignite#2822] opened 2024-10-23 04:23 UTC
### Describe the bug

Issue Body
Description: I'm encountering an error when trying to set up a new Ignite project on Windows. The command rm -rf src fails because the rm command is not recognized in the Windows environment.

Steps to Reproduce:

Run the following command to create a new Ignite project:

npx ignite-cli@latest new todo-app

Follow the prompts to configure the project.
The setup fails during the "Removing fancy demo code" step, resulting in the following error message:

Error: Command failed: rm -rf src
'rm' is not recognized as an internal or external command,
operable program or batch file.
Expected Behavior: The project should be created successfully without encountering errors related to file removal commands that are not recognized on Windows.

Environment:

Platform: Windows
Node Version: 20.15.1
Yarn Version: 1.22.22
Ignite CLI Version: 10.0.1
Git Version: 2.42.0
Additional Information: It seems that the Ignite CLI is using Unix-specific commands that are not compatible with Windows. 

Thank you for your assistance!

### Ignite version

10.0.0

### Additional info

System
  platform           win32
  arch               x64
  cpu                12 cores     AMD Ryzen 5 7535HS with Radeon Graphics
  directory          todo-app     C:\Users\hp\Documents\Projects\todo3\todo-app

JavaScript (and globally-installed packages)
  node                        20.15.1                                   C:\Program Files\nodejs\node.EXE
  npm                         10.8.1                                    C:\Program Files\nodejs\npm.CMD
    @doko-js/cli              0.1.0
    create-react-native-app   4.0.0
    eas-cli                   12.5.1
    expo-cli                  -
    expo                      51.0.32
    http-server               14.1.1
    ignite-cli                10.0.0
    node-openssl              0.0.2-security
    nodemon                   3.0.2
    npm-check-updates         16.14.20
    npm                       10.8.1
    openssl                   2.0.0
    pnpm                      9.5.0
    react-native-cli          2.0.1
    typescript                5.6.3
    vercel                    34.2.8
    yarn                      1.22.22
  yarn                        1.22.22                                   C:\Users\hp\AppData\Roaming\npm\yarn.CMD
    create-react-native-app   3.9.0
    react-native-cli          2.0.1
  pnpm                        9.5.0                                     C:\Users\hp\AppData\Roaming\npm\pnpm.CMD
                              <no pnpm global package info available>
  bun                         -                                         not installed
  expo                        -                                         not installed

Ignite
  ignite-cli         10.0.1       C:\Users\hp\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\.bin\ignite.CMD        
  ignite src         build        C:\Users\hp\AppData\Local\npm-cache\_npx\bec2839915ba8fc3\node_modules\ignite-cli\build       

Android
  java               11.0.2       C:\Users\hp\AppData\Local\jdk-11.0.2\bin\java.EXE
  android home       -            C:\Users\hp\AppData\Local\Android\Sdk

Tools
  git                git version 2.42.0.windows.2   C:\Program Files\Git\cmd\git.EXE

**Comment by frankcalise** [comment] 2024-10-23 05:44
Duplicate of #2816

**Closed** 2024-10-23 05:44 UTC
Labels: bug
