### ISSUE TITLE
Quick Example Generates Wrong Names

### ISSUE THREAD

**Issue by NikitaVr** [infinitered/ignite#1070] opened 2017-05-27 16:43 UTC
---
What's going on?

The Quick Example in the ReadMe generates the wrong names 

For example:
import React from 'react'
import { ScrollView, Text, KeyboardAvoidingView } from 'react-native'
import { connect } from 'react-redux'
// Add Actions - replace 'Your' with whatever your reducer is called :)
// import YourActions from '../Redux/YourRedux'

// Styles
import styles from './Styles/PizzaLocationListScreenScreenStyle'

class PizzaLocationListScreenScreen extends React.Component {
  render () {
    return (
      <ScrollView style={styles.container}>
        <KeyboardAvoidingView behavior='position'>
          <Text>PizzaLocationListScreen Screen</Text>
        </KeyboardAvoidingView>
      </ScrollView>
    )
  }
} 

Notice the `ScreenScreen` in the above, which causes an error when importing since the style file is called `PizzaLocationListScreenStyle.js`
---
Steps to reproduce

Follow the exact steps on the ReadMe for Quick Example, then try to run the app on android.

---
`ignite doctor` results:

ignite doctor
System
  platform           win32
  arch               x64
  cpu                8 cores             Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  directory          C:\React\PizzaApp

JavaScript
  node               7.10.0       C:\Program Files\nodejs\node.EXE
  npm                4.2.0        C:\Program Files\nodejs\npm.CMD
  yarn               0.23.4       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.42.0

Ignite
  ignite             2.0.0-rc.2   C:\Users\nvara\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\Program Files\Java\jdk1.8.0_131\bin\java.EXE
  android home       -            C:\Users\nvara\AppData\Local\Android\sdk

**Comment by GantMan** [comment] 2017-05-27 22:32
Yup, looks like someone made a mistake.  We'll have this fixed this weekend.

**Comment by GantMan** [comment] 2017-05-29 17:46
## PRs incoming:
Fix for this one symptom:  https://github.com/infinitered/ignite-ir-boilerplate/pull/72
Fix for the cause early-detection: https://github.com/infinitered/ignite/pull/1072

**Comment by GantMan** [comment] 2017-05-30 14:43
@NikitaVr - Fixed and new tests in place!

**Closed by GantMan** 2017-05-30 14:43 UTC
Labels: bug, high priority
