### ISSUE TITLE
un able to make app ignite

### ISSUE THREAD

**Issue by CodeBunny786** [infinitered/ignite#1604] opened 2021-02-02 12:22 UTC
What's going on?
un able to create new app

Steps to reproduce

1.creat e new app

---
reslt are fine from doctor results:

**Comment by CodeBunny786** [comment] 2021-02-02 12:23
![Uploading Screenshot 2021-02-02 at 5.27.11 PM.png…]()

**Comment by CodeBunny786** [comment] 2021-02-03 06:52
please help and check thanks

**Comment by flexbox** [comment] 2021-02-09 10:40
Hey @CodeBunny786 
Can you provide the output of
```
ignite doctor
```
AND the error message like in https://github.com/infinitered/ignite/issues/1603

Otherwise, it's impossible to give you any help 😉

**Comment by NatBNW** [comment] 2021-02-11 22:00
Did you find a solution?  After many error codes and fixes, I'm no longer receiving error codes.  It says it is igniting app and then nothing happens.

**Comment by ScoreFootball91** [comment] 2021-02-12 06:15
Yeah same here @flexbox here is ignite doctor results


System
  platform           darwin                                                 
  arch               x64                                                    
  cpu                8 cores      Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz 
  directory          apple        /Users/apple                              

JavaScript
  node               10.16.3      /usr/local/bin/node 
  npm                6.9.0        /usr/local/bin/npm  
  yarn               1.9.4        /usr/local/bin/yarn 

Ignite
  ignite-cli         3.5.1        /usr/local/bin/ignite                                          
  ignite src         build        /Users/apple/.config/yarn/global/node_modules/ignite-cli/build 
  generators         {}                                                                          

Android
  java               1.8.0_201    /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.2       
  cocoapods          1.9.3        /usr/local/bin/pod

**Comment by ScoreFootball91** [comment] 2021-02-12 06:17
<img width="567" alt="Screenshot 2021-02-12 at 11 24 58 AM" src="https://user-images.githubusercontent.com/78295616/107736410-cf0dc080-6d23-11eb-9538-1f36663df037.png">

**Comment by CodeBunny786** [comment] 2021-02-12 07:49
<img width="1440" alt="Screenshot 2021-02-12 at 11 38 47 AM" src="https://user-images.githubusercontent.com/56582059/107742404-c7084d80-6d30-11eb-982d-5c891ecb8485.png">

**Comment by CodeBunny786** [comment] 2021-02-12 07:50
still un bale to make app

**Comment by flexbox** [comment] 2021-02-12 08:04
Can you update to the last CocoaPods version `1.10.1` with
```
gem update cocoapods
```

https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md

**Comment by CodeBunny786** [comment] 2021-02-12 12:04
Thanks alot man let me try

**Comment by NatBNW** [comment] 2021-02-12 18:25
@CodeBunny786 you're not alone.  I'm getting the exact same error messages.  I updated Cocoapods and nothing has changed.  Did updating Cocoapods work for you?

**Comment by CodeBunny786** [comment] 2021-02-15 05:11
@NatBNW Still unable to make one i have updated the Cocoapods

**Comment by NatBNW** [comment] 2021-02-16 00:19
@CodeBunny786 thanks for asking!  I finally got it working!

**Comment by CodeBunny786** [comment] 2021-02-16 14:42
how can you please share ?
@NatBNW

**Comment by CodeBunny786** [comment] 2021-02-16 18:06
<img width="277" alt="Screen Shot 2021-02-08 at 2 15 16 AM" src="https://user-images.githubusercontent.com/56582059/108103074-396b8b80-70ab-11eb-9439-d30e8acbfa09.png">

**Comment by CodeBunny786** [comment] 2021-02-16 18:17
![Uploading Screen Shot 2021-02-16 at 11.03.25 PM.png…]()

**Comment by NatBNW** [comment] 2021-02-16 18:25
@CodeBunny786  I uninstalled EVERYTHING.  I uninstalled React Native (this wasn't easy.  It was hiding. My cmd line search kept telling me it was gone (it wasn't) and I had to go digging for it.  Once I finally had everything related to Ignite and React Native including cocoa pods etc.  I used these instructions and it finally worked.  Let me know if you need help accessing the article. Let me know how it goes!    https://shift.infinite.red/creating-a-trivia-app-with-ignite-bowser-part-1-1987cc6e93a1

**Comment by flexbox** [comment] 2021-02-17 07:27
And for the setup guide on macOS and Windows everything is available https://academy.infinite.red/courses

**Comment by CodeBunny786** [comment] 2021-02-19 06:40
@flexbox @NatBNW  Thanks guys let me reinstall it and give it try again

**Comment by vantuan88291** [comment] 2021-02-20 08:25
the same issue here

**Comment by vantuan88291** [comment] 2021-02-20 08:57
Seem like you are using node old version, after i've upgraded from node 12 to node 14 newest, it be fine, let try it

**Comment by Eunoseer** [comment] 2021-02-21 00:57
I can confirm that I am having this issue as well with a fresh install of everything this morning. A different error though? I have also confirmed that there is no later version of cocoapods to retrieve.

![Screen Shot 2021-02-21 at 10 54 16 am](https://user-images.githubusercontent.com/45803717/108612317-34a03200-7433-11eb-9598-0b4706bcc1a9.png)
![Screen Shot 2021-02-21 at 10 54 07 am](https://user-images.githubusercontent.com/45803717/108612318-37028c00-7433-11eb-9e82-3d8638a1ac0b.png)

**Comment by Xandroid4Net** [comment] 2021-02-22 23:35
@Eunoseer I had the exact same issue as you reported. I had to run the following
npm install -g ignite-cli
brew install yarn

Once I did that the ignite cli would generate the app, build it and deploy. Now I have to figure out the no bundle url present error. I know its not working but hopefully this gets you a bit farther along.
![Simulator Screen Shot - iPhone 11 - 2021-02-22 at 15 34 24](https://user-images.githubusercontent.com/5997627/108784134-8e802500-7523-11eb-9dae-9062c9290a1a.png)

**Comment by cjinghong** [comment] 2021-02-23 10:02
I'm having the same exact issue

**Comment by cjinghong** [comment] 2021-02-23 10:14
I've resolved the issue, please make sure you have the correct `react-native-cli` installed. 

Remove incorrect react-native-cli
`yarn global remove react-native-cli` or `npm uninstall -g react-native-cli`

Install the correct one
`yarn global add @react-native-community/cli` or `npm install -g @react-native-community/cli`

I think this should be mentioned in the docs somewhere.

**Comment by bryanstearns** [comment] 2021-02-24 00:25
I'm closing this issue because it now covers several distinct problems (most of which are resolved by the people who had them).

If you still have a problem, please make sure you don't have older versions of `react-native-cli` or `ignite-cli` installed globally. If you still have a problem after that, open your own issue, and include the command you ran, all of its output, and the complete output of `ignite doctor` - it really helps.

**Closed by bryanstearns** 2021-02-24 00:25 UTC

**Comment by CodeBunny786** [comment] 2021-03-03 09:26
un able to create app using ignite :(

---

Steps to reproduce

1. npx ignite-cli new PizzaApp


---

`ignite doctor` results:
apple@Apples-MacBook-Pro desktop % ignite doctor          
System
  platform           darwin                                                 
  arch               x64                                                    
  cpu                8 cores      Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz 
  directory          Desktop      /Users/apple/Desktop                      

JavaScript
  node               10.16.3      /usr/local/bin/node 
  npm                6.9.0        /usr/local/bin/npm  
  yarn               1.9.4        /usr/local/bin/yarn 

Ignite
  ignite-cli         3.5.1        /usr/local/bin/ignite                                          
  ignite src         build        /Users/apple/.config/yarn/global/node_modules/ignite-cli/build 
  generators         {}                                                                          

Android
  java               1.8.0_201    /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.2       
  cocoapods          1.10.1       /usr/local/bin/pod 
apple@Apples-MacBook-Pro desktop %
