### ISSUE TITLE
Reactotron doesn't seems to work

### ISSUE THREAD

**Issue by scerelli** [infinitered/ignite#261] opened 2016-07-19 13:45 UTC
I tried to run reactotron but it reutrns 0 clients online. What I did is: 
1) Start iOS (`react-native run-ios`)
2) `npm run tron` and viceversa but the clients conneted are always 0.

I didn't change anything inside the reactotron config so I don't really know why it doesn't works. I even tried to follow the readme on reactotron repo with no luck.

**Comment by skellock** [comment] 2016-07-19 14:13
Is this happening from a freshly Ignited project?

**Comment by scerelli** [comment] 2016-07-19 14:31
Yes i've a project a bit older (like 1 month) where it never worked and a fresh one, same story

**Comment by skellock** [comment] 2016-07-19 14:42
I just ran `ignite n ReactotronTest` and had no problems connecting.

It runs on port 3334.  You running a firewall or something like that?  Maybe multiple NICs? 

Can you telnet to the port when `npm run tron` is running?

![image](https://cloud.githubusercontent.com/assets/68273/16954034/5ca0211e-4d9d-11e6-8e41-6193c3106b4b.png)

**Comment by tmaziere** [comment] 2016-07-19 15:19
Hi,

Same problem here with android , with a quite recent project (few days).
`node_modules/.bin/reactotron` says "0 online".
Telnet returns _404_.

**Comment by skellock** [comment] 2016-07-19 15:21
The telnet means you're connecting fine.  So that's a good sign.

What iOS version are you using on your simulator?

**Comment by tmaziere** [comment] 2016-07-19 15:42
For my part i'm using _Android_, v 6.0 / API 23.

**Comment by skellock** [comment] 2016-07-19 15:44
For Android, if you're using a 5.0-based+ Android OS (which you do) , you can type:

`adb reverse tcp:3334 tcp:3334` to reverse port forward from your simulator back to your device.

Alternatively, in `reactotron 0.7.0`, we now have a way to automatically do this so the reverse isn't needed anymore.  I'll submit this dependency update to Ignite shortly.

**Comment by tmaziere** [comment] 2016-07-19 17:04
Mmh, nothing better with these tips, even upgrading reactotron. I must have missed something important. 
This is what i get when i launch AVD from Android SDK Manager. Is there any clue ? It doesn't seem very clean.
```
Starting emulator for AVD 'react-native'
adb_server_notify: Failed to establish connection to ADB server
emulator: WARNING: VM heap size set below hardware specified minimum of 256MB
emulator: WARNING: Setting VM heap size to 512MB
console on port 5554, ADB on port 5555
```
I would say that there is at least a _port_ issue, don't you ?

**Comment by skellock** [comment] 2016-07-19 19:30
Maybe.  I'm not sure what those log messages are.  They're not `reactotron`.

It just sounds like the emulator can't talk to the reactotron service running on your computer.  

Sounds like I might need to add some debugging tools into the project.

Are you able to have your RN Android app talk to the RN Packager and doing things like live reloading?

**Comment by skellock** [comment] 2016-07-19 19:36
I'm going to close this issue here and open it up on https://github.com/skellock/reactotron/issues/63.  This is more of a Reactotron issue than Ignite.

Thanks for reporting the problem.  I'd love to get you unblocked here.  Just flying blind because I'm unable to reproduce this.  Baking something into Reactotron for debugging seems like a good next step.

**Closed by skellock** 2016-07-19 19:36 UTC
Labels: Info Needed
