### ISSUE TITLE
npm not working while setting up Ignite App with npx ignite-cli@latest new app-name.

### ISSUE THREAD

**Issue by NzakiCodes** [infinitered/ignite#2748] opened 2024-08-18 06:48 UTC
### Describe the bug

I ran into this issues while running `npx ignite-cli@latest new PizzaApp`

The following error occurred:
    
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: pizza-app@0.0.1
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error   peer react@">=16.8.0" from @testing-library/react-native@12.6.0
npm error   node_modules/@testing-library/react-native
npm error     dev @testing-library/react-native@"^12.5.2" from the root project
npm error   1 more (react-native)
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.3.1" from react-test-renderer@18.3.1
npm error node_modules/react-test-renderer
npm error   peer react-test-renderer@">=16.8.0" from @testing-library/react-native@12.6.0
npm error   node_modules/@testing-library/react-native
npm error     dev @testing-library/react-native@"^12.5.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/nzaki/.npm/_logs/2024-08-18T06_26_44_893Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/nzaki/.npm/_logs/2024-08-18T06_26_44_893Z-debug-0.log

I tried it with nut with yarn as the package manager and it ran without issues.

### Ignite version

9.8.2

### Additional info

System
  platform           linux                                                 
  arch               x64                                                   
  cpu                8 cores      Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 
  directory          AppLabs      /home/nzaki/workspace/AppLabs            

JavaScript (and globally-installed packages)
  node               20.16.0      /home/nzaki/.nvm/versions/node/v20.16.0/bin/node 
  npm                10.8.1       /home/nzaki/.nvm/versions/node/v20.16.0/bin/npm  
    corepack         0.28.2                                                        
    npm              10.8.1                                                        
  yarn               -            not installed                                    
  pnpm               -            not installed                                    
  bun                -            not installed                                    
  expo               -            not installed                                    

Ignite
  ignite-cli         9.8.2        /home/nzaki/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /home/nzaki/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               -            null                    
  android home       -            /home/nzaki/Android/Sdk 

Tools
  git                git version 2.42.0   /usr/bin/git

**Comment by vijal-patel** [comment] 2024-08-18 09:44
I have the same issue, I was able to resolve it by bumping react to 18.3.1 and react-native to 0.75. I haven't looked the impact of doing this however since I'm only experimenting with react-native.

I'm happy to investigate what the impact of doing this is and create a PR for the fix if no one has looked at this yet.

**Comment by frankcalise** [comment] 2024-08-18 14:43
Duplicate of #2747

**Closed by frankcalise** 2024-08-18 14:43 UTC
Labels: bug
