### ISSUE TITLE
Make sure you have an Android emulator running or a device connected and have set up your Android development environment

### ISSUE THREAD

**Issue by darijus** [infinitered/ignite#1384] opened 2019-02-21 22:55 UTC
```
BUILD FAILED in 3s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
```

---
`ignite doctor` results:

```System
  platform           win32                                                                                              
  arch               x64                                                                                                
  cpu                8 cores                                         Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  directory          C:\Users\xxx\Projects\AppName                                                   

JavaScript
  node               11.10.0      C:\Program Files\nodejs\node.EXE
  npm                6.7.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.13.0       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.57.7

Ignite
  ignite             2.2.2            C:\Users\xxx\AppData\Local\Yarn\bin\ignite.CMD
  boilerplate        ignite-andross

Android
  java               -            C:\Program Files\Java\jdk1.8.0_201\bin\java.EXE
  android home       -            C:\Users\xxx\AppData\Local\Android\Sdk
```

Doesn't happen on a normal react native app

**Comment by diegotejadav** [comment] 2019-02-22 15:00
@darijus, do you have android studio installed, configured and some virtual device running in the AVD Manager?
I use these and everything runs well:
![screen shot 2019-02-22 at 10 00 09 am](https://user-images.githubusercontent.com/3412546/53250564-a862a500-3688-11e9-9f84-09f1b667e7f0.png)

**Comment by vadim-96** [comment] 2019-03-16 11:15
@darijus first you need to run android emulator from the AVD Manager, then start your project: `react-native run-android`
Don't forget about the android paths: [https://facebook.github.io/react-native/docs/getting-started#4-add-platform-tools-to-path](https://facebook.github.io/react-native/docs/getting-started#4-add-platform-tools-to-path)

**Comment by kevinvangelder** [comment] 2019-04-03 18:59
@darijus By "normal React Native app" do you by chance mean an Expo generated app? If so, you'll probably need to download and install Android Studio, it's dependencies, and the necessary SDKs to get an emulator up and running. Under the hood, we're actually running the same commands to launch the React Native app on your emulator as vanilla React Native, so it is unlikely we have caused the issue you are experiencing.

**Comment by jamonholmgren** [comment] 2019-04-10 17:11
Since this issue is pretty old, I'm going to close it. Please open a new issue if you continue to run into this problem! <3

**Closed by jamonholmgren** 2019-04-10 17:11 UTC
Labels: question

**Comment by certilremy** [comment] 2019-05-16 16:23
I Have the same Problem here. When I create a fresh new app it work , if I close an reopen the app I can't run it keeps telling me this error. I need  to create a fresh app an copy my old code to continue working every time i close my App .

**Comment by jamonholmgren** [comment] 2019-05-21 17:05
@certilremy, that sounds really painful! I'm not sure what we can do here to help you, though. If you provide a fresh Ignite-powered app that reproduces the issue, then we can take a look. Please open a new issue if you do.

**Comment by kukokp** [comment] 2019-06-20 05:56
I open genymotion and device is show in android studio but when i run react-native project then 
"Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:"

This error is showing please guide me for the same

**Comment by GreenRidingHood** [comment] 2020-04-17 01:30
chmod 755 android/gradlew && react-native run-android

Maybe help anyone, I run that line at terminal and solved my issue
https://superuser.com/questions/1399393/i-cant-run-react-native-run-android
