### ISSUE TITLE
native base boiler plate: issue with drawer navigation

### ISSUE THREAD

**Issue by sanchil** [infinitered/ignite#1211] opened 2017-12-21 13:26 UTC
I was developing an app using ignite native base boiler plate and all was fine till about yesterday I tried using an npm library sjcl for encrypting passwords. I realized that sjcl did not work out of the box and needed a few hacks using a library rn-nodeify. Right after that everything went south and I tried to rebuild my codebase from ground up by igniting a new app using ignite-native-base-boilerplate. I even reinstalled a new copy of nodejs and tried out all the usual hacks such as clearing node cache restarting the watchman server etc

watchman watch-del-all
rm -rf /tmp/react-*
rm -rf node_modules/

npm cache clean --force 
or
npm cache verify

npm install
npm start -- --reset-cache

This usually brings my app online but not so this time.

---
Following are the steps to reproduce the error : -

$ignite new igapp7 -b ignite-native-base-boilerplate
$cd igapp7
$react-native run-android 
or
$react-native start 
 - I click on the login button of the login page 
-  I click on the explorer button it fails on the drawer navigator.

I use a physical device to test my app and I click on the login button of the login page and it takes me to the launch screen. On the launch screen when I click on the explorer button it fails on the drawer navigator. The stack navigator seems to be working fine. 

The following the stack trace I receive:

undefined is not an object (evaluating 'route.routeName')
<unknown>
    createConfigGetter.js:51:10
render
    DrawerView.js:190:6
<unknown>
    ReactNativeStack-dev.js:1863:19
measureLifeCyclePerf
    ReactNativeStack-dev.js:1610:15
_renderValidatedComponentWithoutOwnerOrContext
    ReactNativeStack-dev.js:1862:54
_renderValidatedComponent
    ReactNativeStack-dev.js:1872:34
performInitialMount
    ReactNativeStack-dev.js:1696:57
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
updateChildren
    ReactNativeStack-dev.js:2723:79
_reconcilerUpdateChildren
    ReactNativeStack-dev.js:2857:57
_updateChildren
    ReactNativeStack-dev.js:2892:134
updateChildren
    ReactNativeStack-dev.js:2889:29
receiveComponent
    ReactNativeStack-dev.js:2955:28
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
updateChildren
    ReactNativeStack-dev.js:2719:132
_reconcilerUpdateChildren
    ReactNativeStack-dev.js:2857:57
_updateChildren
    ReactNativeStack-dev.js:2892:134
updateChildren
    ReactNativeStack-dev.js:2889:29
receiveComponent
    ReactNativeStack-dev.js:2955:28
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
updateChildren
    ReactNativeStack-dev.js:2719:132
_reconcilerUpdateChildren
    ReactNativeStack-dev.js:2857:57
_updateChildren
    ReactNativeStack-dev.js:2892:134
updateChildren
    ReactNativeStack-dev.js:2889:29
receiveComponent
    ReactNativeStack-dev.js:2955:28
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
receiveComponent
    ReactNativeStack-dev.js:1769:58
receiveComponent
    ReactNativeStack-dev.js:1345:115
_updateRenderedComponentWithNextElement
    ReactNativeStack-dev.js:1844:144
_updateRenderedComponent
    ReactNativeStack-dev.js:1840:53
_performComponentUpdate
    ReactNativeStack-dev.js:1823:221
updateComponent
    ReactNativeStack-dev.js:1804:116
performUpdateIfNecessary
    ReactNativeStack-dev.js:1772:226
performUpdateIfNecessary
    ReactNativeStack-dev.js:1353:50
runBatchedUpdates
    ReactNativeStack-dev.js:1469:51
perform
    ReactNativeStack-dev.js:1382:99
perform
    ReactNativeStack-dev.js:1382:99
perform
    ReactNativeStack-dev.js:1451:40
flushBatchedUpdates
    ReactNativeStack-dev.js:1476:28
closeAll
    ReactNativeStack-dev.js:1412:101
perform
    ReactNativeStack-dev.js:1388:52
batchedUpdates
    ReactNativeStack-dev.js:2077:139
batchedUpdates$1
    ReactNativeStack-dev.js:1456:61
batchedUpdates
    ReactNativeStack-dev.js:699:31
batchedUpdatesWithControlledComponents
    ReactNativeStack-dev.js:708:30
_receiveRootNodeIDEvent
    ReactNativeStack-dev.js:748:46
receiveTouches
    ReactNativeStack-dev.js:762:60
__callFunction
    MessageQueue.js:266:47
<unknown>
    MessageQueue.js:103:26
__guard
    MessageQueue.js:231:6
callFunctionReturnFlushedQueue
    MessageQueue.js:102:17

---
ignite doctor
System
  platform           linux                                                                        
  arch               x64                                                                          
  cpu                4 cores                            Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz  
  directory          /home/azure/spaces/mobile/igapp7                                             

JavaScript
  node               8.9.3        /usr/bin/node  
  npm                5.6.0        /usr/bin/npm   
  yarn               1.3.2        /usr/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.47.2      

Ignite
  ignite             2.0.0        /usr/bin/ignite  

Android
  java               1.8.0_151    /opt/java/jdk1.8.0_151/bin/java  
  android home       -            /home/azure/dev/Android/Sdk

**Comment by ruddell** [comment] 2017-12-21 15:24
Duplicate of https://github.com/GeekyAnts/ignite-native-base-boilerplate/issues/14.  Solution is to pin `react-navigation` to beta 21 or wait for its next release

**Comment by sanchil** [comment] 2017-12-22 06:12
Well ... I upped the version of the navigation package to beta 22, but no luck and the error persists. The default dependencies for the ignite native base boiler plate is as under and react navigation was beta 7. These dependencies seem to the same. So, will all being same then why did it work earlier and why not now?

 "dependencies": {
    "apisauce": "^0.14.0",
    "format-json": "^1.0.3",
    "lodash": "^4.17.2",
    "native-base": "2.3.1",
    "prop-types": "^15.5.10",
    "querystringify": "0.0.4",
    "ramda": "^0.24.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "react-native-config": "^0.6.0",
    "react-native-drawer": "^2.3.0",
    "react-native-i18n": "1.0.0",
    "react-native-vector-icons": "4.3.0",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-persist": "^4.1.0",
    "redux-saga": "^0.15.6",
    "reduxsauce": "0.4.1",
    "seamless-immutable": "^7.0.1"
  },
  "devDependencies": {
    "@storybook/addon-storyshots": "^3.2.3",
    "@storybook/react-native": "^3.2.3",
    "babel-eslint": "7.1.1",
    "babel-jest": "22.0.3",
    "babel-plugin-ignite-ignore-reactotron": "^0.3.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react-native": "3.0.2",
    "enzyme": "^2.6.0",
    "husky": "^0.13.1",
    "ignite-i18n": "^1.1.1",
    "ignite-native-base-boilerplate": "^2.0.0",
    "ignite-standard": "^1.0.0",
    "ignite-vector-icons": "^1.1.0",
    "jest": "22.0.3",
    "mockery": "^2.0.0",
    "react-addons-test-utils": "~15.4.1",
    "react-dom": "16.0.0-alpha.12",
    "react-test-renderer": "16.0.0-alpha.12",
    "reactotron-react-native": "^1.12.0",
    "reactotron-redux": "^1.11.1",
    "reactotron-redux-saga": "^1.11.1",
    "snazzy": "^7.0.0",
    "standard": "10.0.2"
  },

**Comment by ruddell** [comment] 2017-12-22 13:49
Use Beta 21. The issue comes from Beta 22 (which ^1.0.0-Beta.7 resolves to)

**Comment by sanchil** [comment] 2017-12-23 07:16
oooeer .... :-p ... thank u for that lesson on versioning bit @ruddell . I had some perceptions about the package.json hard wired into my mind and completely forgotten about the devilish detail of versioning. So your  suggestion worked for me ... thank u .. :+1:

**Closed** 2018-02-27 10:18 UTC
